### PR TITLE
Complete to currently selected suggestion.

### PR DESCRIPTION
**Pull request by sheeley**
When hitting right (RTL) or left (LTR), rather than simply completing to the top
suggestion, if the user has navigated down to a suggestion, use it. Fall back to
the first suggestion if they haven't.

The current behavior is to complete to the first suggestion no matter what you may have navigated to in the list.

### CODE REVIEW

**Comment by jcrben** [comment]
:+1: 

Hearing no objections, I'll merge this in after waiting a few more days.

**Comment by sheeley** [comment]
Updated this with a `grunt` for dist as well.

**Comment by jcrben** [comment]
@sheeley maybe you should be added as a collaborator as well? seems like you've got some energy and I think the idea is that this is a bit of a broad tent. pinging @lenovouser

**Comment by lenovouser** [comment]
@jcrben Thanks! @sheeley You're invited! Thank you for your contributions!

I am really busy at the moment (New Job, New Apartment etc. etc.) which is why I sadly can't really be helpful a lot here for now. I hope we get [v0.11.2](https://github.com/corejavascript/typeahead.js/milestones/v0.11.2) done as soon as possible though so we can push to bower and npm.

**Comment by sheeley** [comment]
@jcrben, @lenovouser thanks! these are just a couple of changes I made due to work, but happy to help out - I'll take a look at issues under that label, how would you like me to help?

**Pull request merged**
