### PR TITLE
Added new option tabAutocomplete

### PR DESCRIPTION
**Pull request by Artistan**
same update as https://github.com/corejavascript/typeahead.js/pull/77 but without conflicts.
credit --> @Darnokk https://github.com/Darnokk

      - The default behaviour of the TAB-key is to select the top suggestion
      - We introduced a new option called 'tabAutocomplete' which is NOT mandatory and defaults to true.
      - If the option 'tabAutocomplete' is true, the TAB-key will select the top suggestion as usual
      - If the option 'tabAutocomplete' is NOT set, the TAB-key will select the top suggestion as usual
      - Only if you set the option 'tabAutocomplete' to false pressing the TAB key will change the focus on the html-element with the next tabindex.
      - Added option 'tabAutocomplete' to doc
      - Added two methods for tabAutocomplete = true resp. false to the unit-test typeahead_spec.js

### CODE REVIEW

**Comment by Artistan** [comment]
here is a bit of a work-around for anyone looking to allow for "not autocompleting".

https://codepen.io/Artistan/pen/LywrXj

**Comment by jcrben** [comment]
Seems cool, but why the changes to the minified files and the stuff like `typeof exports === "object"`?

**Comment by Darnokk** [comment]
I tested your dist/typeahead.bundle.js and saw no difference in the behaviour, when tabAutocomplete = true/false,
maybe there is a slightly mistake in there?

**Comment by Artistan** [comment]
no longer using... on to other things.

**Pull request closed without merging**
