### PR TITLE
Fix UMD commonjs support

### PR DESCRIPTION
**Pull request by PikachuEXE**
Related issue(s): 
- #112 

This is based on the UMDJS jQuery template available at
https://github.com/umdjs/umd/blob/95563fd6b46f06bda0af143ff67292e7f6ede6b7/templates/jqueryPlugin.js

Similar to https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e

The usage might need to be changed
My current usage of modified `typeahead.js` (with browserify):
```javascript
import $ from "jquery";
require("corejs-typeahead/dist/typeahead.jquery")(window, $)

// $(".something").typeahead({...})
```

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Anyone??

**Comment by PikachuEXE** [comment]
Hello?

**Comment by PikachuEXE** [comment]
No comment at all ?

**Comment by jesperronn** [comment]
I'm sorry, but maybe @jlbooker could review and merge if OK? Unfortunately I am not able to review or test your suggestion, so I hope that others will comment and/or review.

PS. Thanks @PikachuEXE for maintaining the I18n.js rails plugin 👍

**Comment by PikachuEXE** [comment]
Thanks for responding
I am just worried that this repo has no one watching like the twitter one ;P

PS. I maintain `I18n-js` since I use it too :)

**Comment by jlbooker** [comment]
@PikachuEXE I've been too busy to look/test. I don't use it via UMD/require/browserify, so I don't have a good way of testing this. After next week I may have some time to dig in a do proper testing.

**Comment by PikachuEXE** [comment]
I have also invited @bryanrasmussen from #112 to help test this version
But he has no response yet

**Comment by bryanrasmussen** [comment]
hey, didn't see it earlier - have been on family leave. Will check either
today or tomorrow since I am in that code fixing a bug these days.

Thanks,
Bryan Rasmussen

**Comment by bryanrasmussen** [comment]
Ok quick testing showed everything working on my end, although the original problem was one with our codebase and JQuery getting overridden, which not sure if that is something one should want to fix. By finding the error in our codebase I improved it, if Typeahead was solid enough to keep on trucking through that error I might not have noticed it.

**Comment by PikachuEXE** [comment]
I can keep on using my own version for a while 
until there is no more comments on 
https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e

I don't know UMD well so I can only follow what the "big projects" are doing

**Comment by xf039** [comment]
Why is this still open? Is this repository dead as well?

**Comment by PikachuEXE** [comment]
@xf039 
I think [it's already addressed](https://github.com/corejavascript/typeahead.js/commit/155b00f2268638349c1a1e3497a20b084518df43) but forgot to mention in this PR
But let me test before closing this one

**Comment by PikachuEXE** [comment]
Turns out I am using `1.3.x` for a long time (`2019-11-25`)
So I think this can be closed

**Pull request closed without merging**
