### PR TITLE
Limit and flickering fixup, plus add an option to specify the order of the datasets

### PR DESCRIPTION
**Pull request by gaborbernat**
:+1:

### CODE REVIEW

**Comment by ApfelUser** [comment]
@gaborbernat The tests are failing, and I don't really get where the error now comes from. Would you mind looking over that real quick?

**Comment by gaborbernat** [comment]
I will tomorrow.

Bernát GÁBOR

**Comment by CoreSystemDevelopment** [comment]
@gaborbernat any updates?

**Comment by gaborbernat** [comment]
not yet :disappointed:

**Comment by jesperronn** [comment]
@gaborbernat Can you also provide a summary of this pull-request, for others to easily understand what this feature helps or fixes.

**Comment by jcrben** [comment]
@jesperronn Seems like there are a few things going on here. 

7415b626df799179a86b56fef41e0b48dc7a4771 and 5d129fefb05fdf298300817712f776bde5e5c3ba seem to be about the same thing, which is allowing indexing of remote datums. They should be squashed together. from https://github.com/twitter/typeahead.js/issues/1148

f50b06ce4a71dc8b5e43806a0c76bc9bf6f8adf3 makes it easier to use requirejs alias. :+1: 

Not sure on the others - seems like they should be associated with issues if at all possible.

**Comment by cstoneham** [comment]
@gaborbernat any updates here? This would be really great to have in!

**Comment by gaborbernat** [comment]
will try to look into this, just got a lot on my plate in the meantime

Bernát GÁBOR

**Comment by mendelk** [comment]
Any update on this?

**Pull request closed without merging**
