### PR TITLE
Make browser tests work again

### LINKED ISSUE #20: Travis Not running Browser tests
Hi, of the 12 jobs running upon every Pull-request commit, none of the browser specific tests run!

Only the unit-test runs.

For example on #18, the tests ran, but only [travis build 26.1]() actually ran the test suite.

The others (browser based) had the following line in the output:
```
Not running any tests
```

which you can see for instance in [travis build 26.2](https://travis-ci.org/corejavascript/typeahead.js/jobs/85697833) and all the others in the [travis build list]() for #18.

The line in `test/ci` 
https://github.com/corejavascript/typeahead.js/blob/master/test/ci#L5

evaluates to 
```
+'[' false == true -a integration == integration ']'
```

which must mean that `"$TRAVIS_SECURE_ENV_VARS"` is not set.

Who can help setting up the browser tests again?? I'd like to help but am in doubt about who has access to setting it up?

### PR DESCRIPTION
**Pull request by jesperronn**
Adding my Sauce Labs account with the hope to actually test in 11 browsers on Sauce Labs

I am uncertain if this is enough by itself, since the abandoned project had
credentials already (probably from @jharding)

Originally added to twitter/typeahead.js in July 2014
https://github.com/twitter/typeahead.js/commit/f5af04bebac5ffbbc1350c451504529826e31a0b

In case you want to revisit this in 5 years, my saucelab user account is 'jesperronn'

When this PR works, it will fix #20

### CODE REVIEW

**Comment by jesperronn** [comment]
hmm, https://github.com/jesperronn/typeahead.js/commit/42aabc6d9a3c74773e8f7f1201b48f91e15da543 didn't work. The browser tests still don't run since `"$TRAVIS_SECURE_ENV_VARS"` still evaluates to `false`

Will put this PR in WIP until I'm satisfied. Feel free to help :)

**Comment by ApfelUser** [comment]
@jesperronn I think you might need to add 

```
TRAVIS_SECURE_ENV_VARS = true
```

or

```
$TRAVIS_SECURE_ENV_VARS = true
```

to [travis-ci.org:corejavascript/typeahead.js/settings](https://travis-ci.org/corejavascript/typeahead.js/settings).

**Comment by jesperronn** [comment]
Hmm https://github.com/jesperronn/typeahead.js/commit/cddcbbe733ea2d8911873cece70c53662b2ae4e6 did not work either. From the [Travis configuration]() I read that

> Encrypted environment variables are not available to pull requests from forks due to the security
> risk of exposing such information to unknown code.

Which means that this Pull request will never run the saucelabs tests.

**Comment by jlbooker** [comment]
@jesperronn & @ApfelUser Due to the Travis environment var limitation on pull requests noted above, I suggest we just merge this PR and see what happens. It won't break anything in terms of actual functionality.

**Comment by jesperronn** [comment]
@jlbooker & @corejavascript/collaborators Even though this were merged, my preliminary findings show me that I cannot even run these locally... perhaps some package inconsistency. I would love to solve #26 so that we can actually verify the tests locally (just for Phantom or Chrome).

Preferably work on with this after a solution has been provided for #26

**Comment by jlbooker** [comment]
@jesperronn Thanks for the update! (Sorry for the late reply, didn't see the GH notification!)

Moving this to the next milestone so we can get this release out the door. Let's continue working on this.

**Comment by jcrben** [comment]
We should really revive this before merging too many merge requests...

**Comment by jesperronn** [comment]
Closing this as it has been open for ages. Feel free to reopen if you feel this is still relevant.

**Pull request closed without merging**
