### PR TITLE
Add autoselect option

### PR DESCRIPTION
**Pull request by JonathanSeguin**
Fixed merge conflicts for #54

### CODE REVIEW

**Comment by JonathanSeguin** [comment]
@jcrben Squashed. Is this acceptable as is? Should I also commit the built/minified sources (dist)? Bump the version number?

**Comment by jcrben** [comment]
Don't think a version bump is necessary - we can bump the version when a new package is distributed.

Are you interested in becoming a maintainer? Honestly I'm not going to maintain this and it doesn't look like any of the other committers are interested either.

**Comment by JonathanSeguin** [comment]
Sorry, but i've got my hands full atm. Good luck with the hunt! It's a pretty useful project.

**Comment by jlbooker** [comment]
@jcrben I'm still around, have just been busy lately. Thanks for reviewing and merging a few of these PRs!

**Pull request merged**
