### PR TITLE
diacritic-insensitive highlighting

### PR DESCRIPTION
**Pull request by wakingrufus**
This was a PR I opened on the twitter base fork, which was never merged. 
[Link](https://github.com/twitter/typeahead.js/pull/1013)
  This feature was requested by many people.  I was pointed to this fork as them best-maintained fork.  Please let me know if there is anything I should change in my code.

### CODE REVIEW

**Comment by sheeley** [comment]
Makes a whole lot of sense! As a diacritic ignoramus, I'm curious if it's possible to identify them without hardcoding. Could you use a regex like `[.\p{L}]`? Seems like it'd be good to help keep file size down, if possible. Also, could you add some tests?

**Comment by wakingrufus** [comment]
I have added tests.  As for the regex, I am not sure how that could be used.  I figured out how to use regex to identify a diacritic, but the code needs to know which letter to normalize it to, and I don't think the regex helps with that.

**Comment by sheeley** [comment]
LGTM

**Comment by jcrben** [comment]
LGTM - but could you add it to the docs? Should at least go in the options I think https://github.com/corejavascript/typeahead.js/blob/master/doc/bloodhound.md#options

Ideally you could also squash your commits, but that's not a strict requirement.

**Comment by wakingrufus** [comment]
@jcrben, Those docs are the options for bloodhound, but this option is for highlight. It looks like highlight() is called from the getSuggestionsHtml() function within Dataset.  It does not appear that it is possible for the code invoking typeahead or creating a bloodhound to pass in highlight options.  Therefore, I am not sure where the appropriate place to document these options would be.  If I am wrong, please let me know, and I would be happy to document the options in the appropriate place.

**Comment by phlegx** [comment]
+1!!! but I cannot find a documentation how to config typeahead to use e.g. diacriticInsensitive. Do a documentation exists?

**Comment by wakingrufus** [comment]
@phlegx it is passed as an option to highlight(), same as caseSensitive:
`highlight({ node: testNode, pattern: 'xxx', diacriticInsensitive: true });`
However, I am not sure how this option can be passed in from the top level of typeahead. Please see my comment here:
https://github.com/corejavascript/typeahead.js/pull/51#issuecomment-174022503

**Comment by dayze** [comment]
So what do we need to modify to make it accent insensitive ? I saw the highlight function into typeahaed.bundle.js but how can I change `diacriticInsensitive` value ?

**Comment by wakingrufus** [comment]
diacriticInsensitive defaults to true currently. 
Unfortunately it does not appear that it is possible for the code invoking typeahead or creating a bloodhound to pass in highlight options, at this time. I think this will require a refactor to expose the options.
also note: this change was only for highlighting. matching diacriticInsensitive is based on the implementation of your bloodhound.

**Comment by jwallet** [comment]
looks like it does not handle `é` et `É`

**Pull request merged**
