### PR TITLE
Fix custom event arguments

### LINKED ISSUE #63: Event parameters
This pull request seems to be not merged, https://github.com/twitter/typeahead.js/pull/1207
It is a very important bugfix

### PR DESCRIPTION
**Pull request by Tol1**
Unmerged pull request from author of upstream twitter/typeahead.js#1207
Rebased original to be mergeable
Closes #63 and #58

### CODE REVIEW

**Comment by fscq86** [comment]
+1 waiting for this fix

**Comment by JoeyDB** [comment]
Is there any temporary fix until v0.11.2 comes out? Thanks!

**Comment by ThisIsAreku** [comment]
👍  This might be at least merged to a _dev_ branch

**Comment by jlbooker** [comment]
@Tol1 Any chance you could rebase again and update this PR? We're working towards a release soon, and it'd be good to include this fix.

**Comment by Tol1** [comment]
I'll rebase as soon as I have time
Great to hear about new release!

**Comment by Tol1** [comment]
Rebased, this should be mergeable now

**Comment by jlbooker** [comment]
:+1:  Thanks @Tol1 . @CoreSystemDevelopment  Could you give this a review as well?

**Comment by jlbooker** [comment]
Also probably fixes #89

**Comment by aaaa0441** [comment]
Since this repo seems not being maintained. I'll likely switch to the [forked corejavascript/typeahead.js](https://github.com/corejavascript/typeahead.js) repo, which contains the fix.

**Comment by jlbooker** [comment]
Hi @aaaa0441, I think you put your comment on the wrong issue. This _is_ the crejavascript fork that's being maintained. :-)

**Comment by aaaa0441** [comment]
oops, my bad. Thanks, @jlbooker, for keeping this project maintained! =) 👍

**Pull request merged**
