### PR TITLE
update example to link to corejavascript docs

### PR DESCRIPTION
**Pull request by andrewharvey**

### CODE REVIEW

**Comment by jcrben** [comment]
Do you want to become a maintainer? We need to figure out a way to bring more people in. I'm not using this library right now.

**Comment by andrewharvey** [comment]
Sorry actually I'm not using it either, I tried it out and ran into this issue but ended up choosing a different library.

**Comment by jcrben** [comment]
Out of curiosity, what solution did you choose? I'm currently working mostly in ReactJS.

**Comment by andrewharvey** [comment]
https://github.com/tristen/suggestions

**Pull request merged**
