### PR TITLE
Add autoselect feature

### LINKED ISSUE #53: Autoselect first option
It would be nice to enable automatically selecting the first search result, this actually used to happen in typeahead in the past. 

How I envision this to work is that one would intialise typeahead with an `autoSelect` option set to `true` (defaults to `false`).

### PR DESCRIPTION
**Pull request by DanielApt**
Closes #53

### CODE REVIEW

**Comment by jcrben** [comment]
Looks good to me. Might want to update the docs too.

By the way, one way to make the maintainers perhaps more comfortable might be to demo the old and new behavior with a screencast http://www.screencast.com/

**Comment by DanielApt** [comment]
I've updated the typeahead docs [here](https://github.com/DanielApt/typeahead.js/commit/93e030191c51eb3e6b0196451f97650b4e117ec8)

I feel this feature is clear enough to not require a screencast, but happy to do so if you feel it's necessary.

**Comment by DanielApt** [comment]
@jcrben It has been working as expected in production.

**Comment by synth** [comment]
+1 love to see this merged in

**Comment by synth** [comment]
actually, @DanielApt, I built this myself and caught a bug. The onblurred event doesn't have any arguments passed in and thus the referenced $e is undefined.

**Comment by fedesoria** [comment]
```
$('.typeahead').bind('typeahead:render', function() {
  $('.typeahead').typeahead('moveCursor', +1);
});
```

**Comment by MarkHerhold** [comment]
@synth was the event passing issue introduced by this PR or was it a pre-existing 'feature' of the previous code-base? If it is pre-existing and adding the event argument later will not cause a regression, I think this could be merged in. Or am I misunderstanding the situation?

**Comment by synth** [comment]
@MarkHerhold well, this code hasn't changed from twitter's codebase, so I'm pretty sure its always existed this way. :rocket: merge

**Comment by DanielApt** [comment]
Sorry, been a bit out of the loop on this one. Would you want me to add @synth's code snippet to my PR?

**Comment by jlbooker** [comment]
Moving this to the 0.11.3 milestone, since it's not clear if this is ready to go.

@DanielApt and @synth is the onBlur event issue resolved?

**Comment by hutch120** [comment]
Just migrated from the old twitter typeahead for other reasons, but our clients miss this feature. Looking forward to seeing it in the next release.

**Comment by JonathanSeguin** [comment]
+1 when can we see this merged?

**Comment by jlbooker** [comment]
@JonathanSeguin, When the merge conflicts are resolved. :wink: 

I likely won't have time to look at this in the near future. If you or @hutch120 think you're up for it, feel free to resolve the conflicts and submit a new PR. I haven't even had a chance to see how extensive the conflicts are (could be a fairly simple fix).

**Comment by JonathanSeguin** [comment]
@jlbooker See #148 for new PR

**Comment by JonathanSeguin** [comment]
This was recently merged. Move to close.

**Comment by hongz1** [comment]
Thanks guys! Since I added this feature into other repo and haven't check its committed in here...

**Pull request closed without merging**
