### PR TITLE
Fix `.visuallyhidden` not being actually hidden

### PR DESCRIPTION
**Pull request by futpib**
Refs #106 and #104

### CODE REVIEW

**Comment by jlbooker** [comment]
Looks good to me.

@colinrotherham, does this still work for your accessibility requirements?

**Comment by colinrotherham** [comment]
Hi @jlbooker,

I'm against embedding CSS like this in JavaScript, for the following reasons:

1. In future, an alternative "visually hidden" snippet may be recommended, making this superfluous.
2. Embedding CSS stops us providing tailored Firefox, legacy IE or mobile styling behind media queries (we're stuck with these rules and only these)
3. Some users may prefer to see the status. 

This is a job for CSS, not script.

**Comment by futpib** [comment]
@colinrotherham I completely agree that this is better off done with css. But, for better or for worse, this is not how typeahead.js currently works. Just search for '.css' calls over the code base.

What happened with 0.11.1 release was a kind of [semver](http://semver.org/) abuse ("patch" and "minor" version number updates must be backwards compatible). Users already depend on typeahead.js doing it's stuff with inline css and do no expect elements popping out of nowhere with minor version update. Moreover, 0.11.1 does not provide any css files one could include to make typehead work as before out of the box.

Changing approach to styling (disabling all inline styles and requiring users to include a css file) is feasible for a minor update behind an option (disabled by default for smooth updates) or for a major update (then we could explicitly state that user must include provided or custom css).

**Comment by colinrotherham** [comment]
@futpib Agreed.

The status message should really have been a new feature, under a major release number.

You'll need a Windows machine running a JAWS 40 minute trial or VoiceOver for Mac to verify this works before merging. Does everything work still?

Like the other `.css()` (especially font styling) we can consider consolidating those into a future release.

**Comment by jlbooker** [comment]
@futpib The semver abuse is my fault. I didn't realize the message was a breaking change, thus the minor version bump from 1.0.1 to 1.1.0.

I'm in favor of merging this fix now to fix what we broke, and creating a separate issue to look at pulling the styles out into an actual stylesheet in a separate (major version numbered) release.

Does that sound good to everyone?

**Comment by futpib** [comment]
@jlbooker Sounds great.

**Comment by jlbooker** [comment]
@futpib Just published version 1.1.1 on NPM. Have a look!

**Comment by ricardobrandao** [comment]
@jlbooker can you please create a github release?

**Comment by jlbooker** [comment]
@ricardobrandao Done! Sorry about that!

**Pull request merged**
