### PR TITLE
Npm postinstall step to npm to cater for easy setup

### PR DESCRIPTION
**Pull request by jesperronn**
(copied over from https://github.com/twitter/typeahead.js/pull/1406, since that project has comments about being abandoned)

With this change, `npm install` ends by running `bower install`

This means that we can cut down the steps for getting started and running tests. 

Now we are down to:

1. `npm install`
2. `npm test`

(npm postinstall step runs automatically). Read more about npm's hooks here: https://docs.npmjs.com/misc/scripts

This also has changes in `.travis.yml` since installation of bower need to run before `npm install` task

### CODE REVIEW

**Comment by ApfelUser** [comment]
@jesperronn The test are failing, please fix them first.

**Comment by jesperronn** [comment]
@ApfelUser yeah, I see the failing test. Only for the first Firefox integration test. The fail is within the `npm install` (seemingly a network connectivity error). 

Around [Line 1964](https://travis-ci.org/corejavascript/typeahead.js/jobs/85539383#L1964)

```
npm ERR! fetch failed https://registry.npmjs.org/fsevents/-/fsevents-1.0.2.tgz
npm ERR! AssertionError: null == true
npm ERR!     at TLSSocket.socketOnData (_http_client.js:303:3)
npm ERR!     at TLSSocket.EventEmitter.emit (events.js:107:17)
npm ERR!     at TLSSocket.Readable.read (_stream_readable.js:369:10)
npm ERR!     at TLSSocket.socketCloseListener (_http_client.js:224:10)
npm ERR!     at TLSSocket.EventEmitter.emit (events.js:129:20)
npm ERR!     at TCP.close (net.js:461:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/travis/.nvm/v0.11.13/bin/node" "/home/travis/.nvm/v0.11.13/bin/npm" "install"
```

Nothing in the javascript has changed. So nothing could cause this error to happen. I was not aware that Travis had network connectivity flakyness like this.


I guess I will just re-commit with a changed commit text. And cross fingers. For all 12 build jobs.

**Comment by ApfelUser** [comment]
Thanks a lot!

**Comment by valscion** [comment]
This change causes installations without a global `bower` to fail.

```
$ npm i --save corejs-typeahead

> corejs-typeahead@0.11.1 postinstall /path/to/my/app/node_modules/corejs-typeahead
> bower install

sh: bower: command not found
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/vesa/.nvm/versions/node/v4.4.0/bin/node" "/Users/vesa/.nvm/versions/node/v4.4.0/bin/npm" "i" "--save" "corejs-typeahead"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! corejs-typeahead@0.11.1 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the corejs-typeahead@0.11.1 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the corejs-typeahead package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs corejs-typeahead
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls corejs-typeahead
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/my/app/venuu/npm-debug.log
```

**Comment by mathiasbn** [comment]
Am I missing something, or does this mean i need a bower dev-dependency just to consume typeahead in my webapp? I mean I have no need to run your tests.

**Comment by jlbooker** [comment]
Yes, it used to mean you'd need to `npm install -g bower` in order to install this package via npm.

However, this has been fixed recently. See #74 . I'm working with the NPM support staff to claim the package in the npm registry so that we can publish an updated package with this fix.

**Comment by mathiasbn** [comment]
Thank you, and sorry for not looking enough, I can see my observations have been delt with there

**Pull request merged**
